#! /bin/sh

# change default cursor X to pointer
xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &
feh --no-fehbg --bg-fill "$HOME/.config/wall.jpg"
~/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           0
bspc config top_padding          0

bspc config normal_border_color "#282828"
bspc config active_border_color "#98971a"
bspc config focused_border_color "#ebdbb2"
bspc config presel_feedback_color "#928374"

bspc config focus_follows_pointer true
bspc config pointer_follows_focus  true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
